---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "auth-api"
  namespace: "default"
  labels:
    app: "auth-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "auth-api"
  template:
    metadata:
      labels:
        app: "auth-api"
    spec:
      containers:
        - name: "auth-api"
          image: "gcr.io/pay-mta/auth-api:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "auth-api-hpa"
  namespace: "default"
  labels:
    app: "auth-api"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "auth-api"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
---
apiVersion: "networking.k8s.io/v1beta1"
kind: "Ingress"
metadata:
  name: "test-ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: "/testpath"
            backend:
              serviceName: "test"
              servicePort: 80