---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: default
  labels:
    app: auth-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: gcr.io/pay-mta/auth-api:latest
          imagePullPolicy: IfNotPresent
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-api-hpa
  namespace: default
  labels:
    app: auth-api
spec:
  scaleTargetRef:
    kind: Deployment
    name: auth-api
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: default
  labels:
    app: payments-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: gcr.io/pay-mta/payments-api:latest
          imagePullPolicy: IfNotPresent
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: payments-api-hpa
  namespace: default
  labels:
    app: payments-api
spec:
  scaleTargetRef:
    kind: Deployment
    name: payments-api
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80