apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pay-mta-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /first-app/(.*) $1 break;
      rewrite /secondary-app/(.*) /$1 break;
spec:
  rules:
    - http:
        paths:
          - path: /auth
            backend:
              serviceName: auth-api-service
              servicePort: 8080
          - path: /payments
            backend:
              serviceName: payments-api-service
              servicePort: 9090
