apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pay-mta-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /auth/*
            backend:
              serviceName: auth-api-service
              servicePort: 8080
          - path: /payments/*
            backend:
              serviceName: payments-api-service
              servicePort: 9090
