---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: default
  labels:
    app: payments-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: gcr.io/pay-mta/payments-api:latest
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: payments-api-hpa
  namespace: default
  labels:
    app: payments-api
spec:
  scaleTargetRef:
    kind: Deployment
    name: payments-api
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 90
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api-service
  namespace: default
  labels:
    app: payments-api
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: payments-api
  type: LoadBalancer