steps:
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy:stable"
  args:
    - run
    - --filename=k8s/auth-api-deployment.yaml
    - --location=us-central1-a
    - --cluster=pay-mta
