steps:
# deploy auth-api image to GKE
- name: "gcr.io/cloud-builders/gke-deploy:stable"
  args:
    - run
    - --filename=k8s/deployments.yaml
    - --location=us-central1-a
    - --cluster=pay-mta
    - run
    - --filename=k8s/ingress.yaml
    - --location=us-central1-a
    - --cluster=pay-mta