steps:

  ### Apply configs
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', '../k8s/' ]
    env:
    - 'CLOUDSD_CONTAINER_CLUSTER=pay-mta'
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'

  #### update images in GKE
  ## auth-api
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'auth-api', 'auth-api=gcr.io/$PROJECT_ID/auth-api']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=pay-mta'